### ISSUE TITLE
Request new nasm package

### ISSUE THREAD

**Issue by ghost** [cygwinports/nasm#1]
Please update the NASM (Netwide Assembler) package. Current version is:

> 2.10.07 (Jan 2013)

x264 now requires at least:

> 2.13 (Apr 2017)

References:

- http://github.com/cygwinports/nasm
- http://github.com/mirror/x264/commit/d2b5f48
- http://nasm.us/pub/nasm/releasebuilds

**Comment by yselkowitz** [comment]
The Cygwin nasm package is maintained by someone else, this is here just for reference.  Please send a request to the mailing list.
